name: javadoc
on:
  workflow_dispatch:
  workflow_run:
    workflows: [maven]
    branches: [main]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 16
          distribution: zulu
      - name: Build with Maven
        run: |
          cd fernflower-gui
          mvn clean javadoc:jar -f pom.xml
      - name: Configure git
        run: |
          git config user.email "not@actual.person"
          git config user.name "GH Actions Bot"
      - name: Commit javadocs
        run: |
          git fetch
          git checkout -t origin/gh-pages
          rm -rf javadoc
          mv fernflower-gui/target/apidocs javadoc
          git add javadoc
          git commit -m "Update javadoc for commit ${{ github.sha }}"
          git push
